# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  webhid-for-firefox = {
    pname = "webhid-for-firefox";
    version = "b4b386631daab468b5bb57e2672c3c22a06ade66";
    src = fetchFromGitHub {
      owner = "Sainan";
      repo = "WebHID-for-Firefox";
      rev = "b4b386631daab468b5bb57e2672c3c22a06ade66";
      fetchSubmodules = true;
      sha256 = "sha256-7VYyXj1klLTjL5XFkIKcyq6eQttJAmUI8rMyeZfwimo=";
    };
  };
}
